### PR TITLE
patch: for tinygo wasip2 support

### PR DESCRIPTION
**Pull request by dipankardas011**
## Task description

patch for commands used to wasm-bindgen and wasm-tools

### CODE REVIEW

**Review by itowlson — APPROVED** [review]
Thanks for catching this!

**Comment by rylev** [comment]
@dipankardas011 is there a reason this PR is marked as a draft?

**Comment by dipankardas011** [comment]
> @dipankardas011 is there a reason this PR is marked as a draft?

Actually I am trying the tinygo wasip2 so once I have read completely I will make it open

**Comment by dipankardas011** [comment]
Finalized the PR

**Review by itowlson — APPROVED** [review]

**Review by kate-goldenring — APPROVED** [review]
Thanks for catching these @dipankardas011

**Pull request merged**
